export { Line2 } from './line2/type'
export { Line3 } from './line3/type'
export { Mat4 } from './mat4/type'
export { Plane } from './plane/type'
export { Vec1 } from './vec1/type'
export { Vec2 } from './vec2/type'
export { Vec3 } from './vec3/type'
export { Vec4 } from './vec4/type'
