export { clone } from './clone'
export { closestPoint } from './closestPoint'
export { copy } from './copy'
export { create } from './create'
export { direction } from './direction'
export { distanceToPoint } from './distanceToPoint'
export { equals } from './equals'
export { fromPoints } from './fromPoints'
export { fromValues } from './fromValues'
export { intersectPointOfLines } from './intersectPointOfLines'
export { origin } from './origin'
export { reverse } from './reverse'
export { toString } from './toString'
export { transform } from './transform'
export { xAtY } from './xAtY'

export { Line2 } from './type'
export as namespace line2
