prefer-workspace-packages: true
packages:
  - "packages/array-utils"
  - "packages/cli"
  - "packages/core"
  - "packages/io/io"
  - "packages/io/io-utils"
  - "packages/io/3mf-deserializer"
  - "packages/io/3mf-serializer"
  - "packages/io/dxf-deserializer"
  - "packages/io/dxf-serializer"
  - "packages/io/json-deserializer"
  - "packages/io/json-serializer"
  - "packages/io/obj-deserializer"
  - "packages/io/obj-serializer"
  - "packages/io/stl-deserializer"
  - "packages/io/stl-serializer"
  - "packages/io/svg-deserializer"
  - "packages/io/svg-serializer"
  - "packages/io/x3d-deserializer"
  - "packages/io/x3d-serializer"
  - "packages/modeling"
  - "packages/utils/img"
  - "packages/utils/regl-renderer"
