export { calculatePlane } from './calculatePlane'
export { clone } from './clone'
export { create } from './create'
export { equals } from './equals'
export { fromGeom2 } from './fromGeom2'
export { fromPoints } from './fromPoints'
export { isA } from './isA'
export { reverse } from './reverse'
export { toEdges } from './toEdges'
export { toPoints } from './toPoints'
export { toPolygons } from './toPolygons'
export { toString } from './toString'
export { transform } from './transform'

export { Slice } from './type'
