export type RGB = [number, number, number]
export type RGBA = [number, number, number, number]
export type HSL = [number, number, number]
export type HSLA = [number, number, number, number]
export type HSV = [number, number, number]
export type HSVA = [number, number, number, number]
