_Sidebar.md:	User-Guide.md autoTOC Makefile
	./autoTOC < User-Guide.md > _Sidebar.md

push::
	git remote set-url origin git@github.com:Spiritdude/OpenJSCAD.org.wiki.git
	git push -u origin master

pull::
	git remote set-url origin git@github.com:Spiritdude/OpenJSCAD.org.wiki.git
	git pull -u origin master
