export * as geom2 from './geom2/index.js'
export * as geom3 from './geom3/index.js'
export * as path2 from './path2/index.js'
export * as path3 from './path3/index.js'
export * as poly2 from './poly2/index.js'
export * as poly3 from './poly3/index.js'
export * as slice from './slice/index.js'
