export { arc, ArcOptions } from './arc'
export { circle, CircleOptions } from './circle'
export { cube, CubeOptions } from './cube'
export { cuboid, CuboidOptions } from './cuboid'
export { cylinder, CylinderOptions } from './cylinder'
export { cylinderElliptic, CylinderEllipticOptions } from './cylinderElliptic'
export { ellipse, EllipseOptions } from './ellipse'
export { ellipsoid, EllipsoidOptions } from './ellipsoid'
export { geodesicSphere, GeodesicSphereOptions } from './geodesicSphere'
export { line } from './line'
export { polygon, PolygonOptions } from './polygon'
export { polyhedron, PolyhedronOptions } from './polyhedron'
export { rectangle, RectangleOptions } from './rectangle'
export { roundedCuboid, RoundedCuboidOptions } from './roundedCuboid'
export { roundedCylinder, RoundedCylinderOptions } from './roundedCylinder'
export { roundedRectangle, RoundedRectangleOptions } from './roundedRectangle'
export { sphere, SphereOptions } from './sphere'
export { square, SquareOptions } from './square'
export { star, StarOptions } from './star'
export { torus, TorusOptions } from './torus'
export { triangle, TriangleOptions } from './triangle'

export as namespace primitives
