export { default as arePointsInside } from './arePointsInside'
export { default as clone } from './clone'
export { default as create } from './create'
export { default as isA } from './isA'
export { default as isConvex } from './isConvex'
export { default as isSimple } from './isSimple'
export { default as measureArea } from './measureArea'
export { default as measureBoundingBox } from './measureBoundingBox'
export { default as reverse } from './reverse'
export { default as toPoints } from './toPoints'
export { default as toString } from './toString'
export { default as transform } from './transform'
export { default as validate } from './validate'

export { default as Poly2 } from './type'
export as namespace poly2
