export { arePointsInside } from './arePointsInside'
export { clone } from './clone'
export { create } from './create'
export { isA } from './isA'
export { isConvex } from './isConvex'
export { isSimple } from './isSimple'
export { measureArea } from './measureArea'
export { measureBoundingBox } from './measureBoundingBox'
export { reverse } from './reverse'
export { toPoints } from './toPoints'
export { toString } from './toString'
export { transform } from './transform'
export { validate } from './validate'

export { Poly2 } from './type'
export as namespace poly2
