export const background: number[]
export const meshColor: number[]
export const lightColor: number[]
export const lightDirection: number[]
export const lightPosition: number[]
export const ambientLightAmount: number
export const diffuseLightAmount: number
export const specularLightAmount: number
export const materialShininess: number
