export const background = [1, 1, 1, 1]
export const meshColor = [0, 0.6, 1, 1] // default face color or line color
export const lightColor = [1, 1, 1, 1] // note: for now there is a single preset light, not an entity
export const lightDirection = [0.2, 0.2, 1]
export const lightPosition = [100, 200, 100]
export const ambientLightAmount = 0.3
export const diffuseLightAmount = 0.89
export const specularLightAmount = 0.16
export const materialShininess = 8.0
