const test = require('ava')

const { colors, geometries, primitives } = require('@jscad/modeling')

const serializer = require('../index.js')

test('serialize 3D geometry to amf', (t) => {
  const emptyShape = geometries.geom3.create()
  const observed1 = serializer.serialize({}, emptyShape)
  t.deepEqual(observed1, expected1)

  const testCube = primitives.cube()
  const observed2 = serializer.serialize({}, testCube)
  t.deepEqual(observed2, expected2)

  const coloredCube = colors.colorize([1.0, 0.0, 0.5, 0.8], testCube)
  const observed3 = serializer.serialize({ unit: 'inch' }, coloredCube)
  t.deepEqual(observed3, expected3)
})

const expected1 = [
  `<?xml version="1.0" encoding="UTF-8"?>
<amf unit="millimeter" version="1.1">
  <metadata type="author">Created by JSCAD</metadata>
</amf>
`
]

const expected2 = [
  `<?xml version="1.0" encoding="UTF-8"?>
<amf unit="millimeter" version="1.1">
  <metadata type="author">Created by JSCAD</metadata>
  <object id="0">
    <mesh>
      <vertices>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
      </vertices>
      <volume>
        <triangle>
          <v1>0</v1>
          <v2>1</v2>
          <v3>2</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>3</v1>
          <v2>4</v2>
          <v3>5</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>6</v1>
          <v2>7</v2>
          <v3>8</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>9</v1>
          <v2>10</v2>
          <v3>11</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>12</v1>
          <v2>13</v2>
          <v3>14</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>15</v1>
          <v2>16</v2>
          <v3>17</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>18</v1>
          <v2>19</v2>
          <v3>20</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>21</v1>
          <v2>22</v2>
          <v3>23</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>24</v1>
          <v2>25</v2>
          <v3>26</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>27</v1>
          <v2>28</v2>
          <v3>29</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>30</v1>
          <v2>31</v2>
          <v3>32</v3>
        </triangle>
      </volume>
      <volume>
        <triangle>
          <v1>33</v1>
          <v2>34</v2>
          <v3>35</v3>
        </triangle>
      </volume>
    </mesh>
  </object>
</amf>
`
]

const expected3 = [
  `<?xml version="1.0" encoding="UTF-8"?>
<amf unit="inch" version="1.1">
  <metadata type="author">Created by JSCAD</metadata>
  <object id="0">
    <mesh>
      <vertices>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>-1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>-1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>-1</x>
            <y>1</y>
            <z>1</z>
          </coordinates>
        </vertex>
      </vertices>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>0</v1>
          <v2>1</v2>
          <v3>2</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>3</v1>
          <v2>4</v2>
          <v3>5</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>6</v1>
          <v2>7</v2>
          <v3>8</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>9</v1>
          <v2>10</v2>
          <v3>11</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>12</v1>
          <v2>13</v2>
          <v3>14</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>15</v1>
          <v2>16</v2>
          <v3>17</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>18</v1>
          <v2>19</v2>
          <v3>20</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>21</v1>
          <v2>22</v2>
          <v3>23</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>24</v1>
          <v2>25</v2>
          <v3>26</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>27</v1>
          <v2>28</v2>
          <v3>29</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>30</v1>
          <v2>31</v2>
          <v3>32</v3>
        </triangle>
      </volume>
      <volume>
        <color>
          <r>1</r>
          <g>0</g>
          <b>0.5</b>
          <a>0.8</a>
        </color>
        <triangle>
          <v1>33</v1>
          <v2>34</v2>
          <v3>35</v3>
        </triangle>
      </volume>
    </mesh>
  </object>
</amf>
`
]
