const test = require('ava')
const {CAG, CSG} = require('@jscad/csg')
const serializer = require('./index.js')

test('serialize ag/csg objects to svg (path: simple)', function (t) {
  const source = function main (params) {
    var cag0 = new CAG()
    var cag00 = new CAG()
    var cag001 = new CSG.Path2D([[42.33333, 0]], false)
    cag001 = cag001.appendPoint([21.166665, -56.44443999999999])
    cag001 = cag001.appendPoint([63.49999499999999, -56.44443999999999])
    cag001 = cag001.close()
    cag001 = cag001.innerToCAG()
    cag00 = cag00.union(cag001)
    cag0 = cag0.union(cag00)
    return cag0
  }

  const expected = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by OpenJSCAD.org -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">
<svg width="42.333mm" height="56.444mm" viewBox="0 0 42.333 56.444" version="1.1" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g>
    <path d="M0 56.44443999999999L21.166665 0L42.33332999999999 56.44443999999999L0 56.44443999999999"/>
  </g>
</svg>
`

  const observed = serializer.serialize(source(), undefined, {output: 'jscad', addMetaData: false})
  t.deepEqual(expected, observed)
})
