export { default as clone } from './clone'
export { default as create } from './create'
export { default as fromPointsConvex } from './fromPointsConvex'
export { default as fromPoints } from './fromPoints'
export { default as fromCompactBinary } from './fromCompactBinary'
export { default as invert } from './invert'
export { default as isA } from './isA'
export { default as toPoints } from './toPoints'
export { default as toPolygons } from './toPolygons'
export { default as toString } from './toString'
export { default as toCompactBinary } from './toCompactBinary'
export { default as transform } from './transform'
export { default as validate } from './validate'

export { default as Geom3 } from './type'
export as namespace geom3
