module.exports = {
  clone: require('../vec4/clone'),
  create: require('../vec4/create'),
  equals: require('./equals'),
  flip: require('./flip'),
  fromData: require('./fromData'),
  fromNormalAndPoint: require('./fromNormalAndPoint'),
  fromObject: require('./fromObject'),
  fromPoints: require('./fromPoints'),
  fromValues: require('../vec4/fromValues'),
  fromVector3Ds: require('./fromVector3Ds'),
  signedDistanceToPoint: require('./signedDistanceToPoint'),
  toString: require('../vec4/toString'),
  transformMat4: require('./transformMat4'),
}
