export { default as appendArc, AppendArcOptions } from './appendArc'
export { default as appendBezier, AppendBezierOptions } from './appendBezier'
export { default as appendPoints } from './appendPoints'
export { default as clone } from './clone'
export { default as close } from './close'
export { default as concat } from './concat'
export { default as create } from './create'
export { default as equals } from './equals'
export { default as fromPoints, FromPointsOptions } from './fromPoints'
export { default as fromCompactBinary } from './fromCompactBinary'
export { default as isA } from './isA'
export { default as reverse } from './reverse'
export { default as toPoints } from './toPoints'
export { default as toString } from './toString'
export { default as toCompactBinary } from './toCompactBinary'
export { default as transform } from './transform'
export { default as validate } from './validate'

export { default as Path2 } from './type'
export as namespace path2
