export { appendArc, AppendArcOptions } from './appendArc'
export { appendBezier, AppendBezierOptions } from './appendBezier'
export { appendPoints } from './appendPoints'
export { clone } from './clone'
export { close } from './close'
export { concat } from './concat'
export { create } from './create'
export { equals } from './equals'
export { fromPoints, FromPointsOptions } from './fromPoints'
export { fromCompactBinary } from './fromCompactBinary'
export { isA } from './isA'
export { reverse } from './reverse'
export { toPoints } from './toPoints'
export { toString } from './toString'
export { toCompactBinary } from './toCompactBinary'
export { transform } from './transform'
export { validate } from './validate'

export { Path2 } from './type'
export as namespace path2
