export { clone } from './clone'
export { create } from './create'
export { fromSides } from './fromSides'
export { fromCompactBinary } from './fromCompactBinary'
export { isA } from './isA'
export { reverse } from './reverse'
export { toOutlines } from './toOutlines'
export { toPoints } from './toPoints'
export { toSides } from './toSides'
export { toString } from './toString'
export { toCompactBinary } from './toCompactBinary'
export { transform } from './transform'
export { validate } from './validate'

export { Geom2 } from './type'
export as namespace geom2
