export { clone } from './clone.js'
export { create } from './create.js'
export { fromSides } from './fromSides.js'
export { isA } from './isA.js'
export { reverse } from './reverse.js'
export { toOutlines } from './toOutlines.js'
export { toPoints } from './toPoints.js'
export { toSides } from './toSides.js'
export { toString } from './toString.js'
export { transform } from './transform.js'
export { validate } from './validate.js'

export type { Geom2 } from './type.d.ts'
